version: '3'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chambre_Micro_Service
    ports:
      - "3306:3306"
    networks:
      - chambre_network

  eureka:
    container_name: eureka
    build: .\Eureka
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: "eureka"
    networks:
      - chambre_network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/

  chambre:
    container_name: chambre
    image: chambre-ms
    build:
      context: .\ChambreMS
    restart: always
    ports:
      - "8099:8099"
    networks:
      - chambre_network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/chambre_Micro_Service?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysql-db
      - eureka

  gateway:
    container_name: gateway
    image: gateway-ms
    build:
      context: .\API_Gateway_Server
    restart: always
    ports:
      - "8090:8090"
    networks:
      - chambre_network
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.client.register-with-eureka=true
      - spring.cloud.gateway.routes[0].id=chambreMS
      - spring.cloud.gateway.routes[0].uri=http://chambre:8099
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/chambre/**
    depends_on:
      - eureka

networks:
  chambre_network:
    driver: bridge
